## Primera clase en Python3
##### Ecuación del calor
$$\alpha  u_{xx} = u_t $$

In [1]:
print('Primera clase en Python3')

Primera clase en Python3


In [8]:
a = 5

In [9]:
a

5

In [10]:
type(a)

int

In [11]:
cadena = 'esto es una cadena'

In [12]:
cadena

'esto es una cadena'

In [13]:
type(cadena)

str

In [14]:
# flotantes
x = 1.0
type(x)

float

In [15]:
import numpy as np

In [16]:
np.pi

3.141592653589793

In [17]:
a = np.array([1,2,3,4])

In [18]:
a

array([1, 2, 3, 4])

In [19]:
type(a)

numpy.ndarray

In [30]:
a[1:]

array([2, 3, 4])

In [31]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [32]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
A[1][1]

5

In [37]:
import scipy.linalg as linalg

$A x = b$

In [35]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([1,2,3])

In [39]:
x = linalg.solve(A, b)
x

C:\Anaconda3\lib\site-packages\scipy\linalg\basic.py:40: RuntimeWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number/precision: 2.2028234615578505e-18 / 1.1102230246251565e-16
  RuntimeWarning)


array([-0.23333333,  0.46666667,  0.1       ])

In [40]:
np.dot(A, x)

array([1., 2., 3.])

In [46]:
u0 = np.linspace(0,1,5); u0

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [45]:
u0

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [48]:
t = np.linspace(0,0.3,4); t

array([0. , 0.1, 0.2, 0.3])

In [49]:
X,Y = np.meshgrid(u0,t)

In [50]:
X

array([[0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ]])

In [51]:
Y

array([[0. , 0. , 0. , 0. , 0. ],
       [0.1, 0.1, 0.1, 0.1, 0.1],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.3, 0.3, 0.3, 0.3, 0.3]])