In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [0]:
L = 1
T = 0.5  #tiempo max
dx = h = 0.1
dt = k = 0.01
alfa = 1

In [3]:
r = round(alfa*k/h**2,7); r

1.0

In [4]:
# valores frontera
m = round(L/dx) + 1
n = round(T/dt) + 1
print(m,n)

11 51


In [5]:
x = np.linspace(0,L,m); x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [6]:
%%time
sol = np.zeros((n,m))  #matriz con las soluciones aproximadas
w = np.zeros(m)  #reserva para el valor inicial
for i in range(m):
    w[i] = round(np.sin(np.pi*x[i]),8)
sol[0] = w.copy()
sol[0]

CPU times: user 0 ns, sys: 1 ms, total: 1 ms
Wall time: 437 µs


In [7]:
def tridiag(a,b,c,N):
    A = np.zeros([N,N])
    np.fill_diagonal(A[1:,:-1],a)
    np.fill_diagonal(A[:-1,1:],c)
    np.fill_diagonal(A,b)
    return A

A = tridiag(-r/2,1+r,-r/2,m-2)
A

array([[ 2. , -0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [-0.5,  2. , -0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. , -0.5,  2. , -0.5,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. , -0.5,  2. , -0.5,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , -0.5,  2. , -0.5,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. , -0.5,  2. , -0.5,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. , -0.5,  2. , -0.5,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. , -0.5,  2. , -0.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. , -0.5,  2. ]])

In [8]:
B = tridiag(r/2,1-r,r/2,m-2)
print(B)

[[0.  0.5 0.  0.  0.  0.  0.  0.  0. ]
 [0.5 0.  0.5 0.  0.  0.  0.  0.  0. ]
 [0.  0.5 0.  0.5 0.  0.  0.  0.  0. ]
 [0.  0.  0.5 0.  0.5 0.  0.  0.  0. ]
 [0.  0.  0.  0.5 0.  0.5 0.  0.  0. ]
 [0.  0.  0.  0.  0.5 0.  0.5 0.  0. ]
 [0.  0.  0.  0.  0.  0.5 0.  0.5 0. ]
 [0.  0.  0.  0.  0.  0.  0.5 0.  0.5]
 [0.  0.  0.  0.  0.  0.  0.  0.5 0. ]]


In [0]:
w1 = np.dot(np.linalg.inv(A), np.dot(B,sol[0][1:-1]))
w1

array([0.28017966, 0.53293338, 0.73351987, 0.86230432, 0.90668042,
       0.86230432, 0.73351987, 0.53293338, 0.28017966])

In [0]:
w2 = np.dot(np.linalg.inv(A), np.dot(B,w1))
w2

array([0.25403341, 0.48320026, 0.6650681 , 0.78183444, 0.82206938,
       0.78183444, 0.6650681 , 0.48320026, 0.25403341])

In [0]:
np.linalg.solve(A,bb )

array([0.28017966, 0.53293338, 0.73351987, 0.86230432, 0.90668042,
       0.86230432, 0.73351987, 0.53293338, 0.28017966])

In [0]:
A_1 = np.linalg.inv(A)

In [0]:
np.dot(A_1*B,sol[0][1:-1] )

array([0.04220108, 0.08444153, 0.11876823, 0.13990258, 0.14712477,
       0.13990258, 0.11876823, 0.08444153, 0.04220108])

In [0]:
temp = np.dot(np.linalg.inv(A)*B,sol[0][1:-1])
temp

array([0.04220108, 0.08444153, 0.11876823, 0.13990258, 0.14712477,
       0.13990258, 0.11876823, 0.08444153, 0.04220108])

In [0]:
temp = np.dot(np.linalg.inv(A)*B, temp)
temp

array([2.69283823e-06, 5.47449619e-06, 7.87967225e-06, 9.45042460e-06,
       9.99040827e-06, 9.45042460e-06, 7.87967225e-06, 5.47449619e-06,
       2.69283823e-06])

In [0]:
np.dot(np.linalg.matrix_power(np.linalg.inv(A)*B,n),sol[0][1:-1])

array([7.13833659e-44, 1.45355218e-43, 2.09635912e-43, 2.51712695e-43,
       2.66345931e-43, 2.51712695e-43, 2.09635912e-43, 1.45355218e-43,
       7.13833659e-44])

In [9]:
%%time
w0 = sol[0][1:-1]
for i in range(n-1):
  temp = np.dot(np.linalg.inv(A),np.dot(B,w0))
  w0 = temp
  
print(temp)

[0.00230512 0.00438461 0.00603489 0.00709444 0.00745954 0.00709444
 0.00603489 0.00438461 0.00230512]
CPU times: user 4 ms, sys: 7 ms, total: 11 ms
Wall time: 11.4 ms


In [0]:
m

11

In [12]:
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [10]:
u = x.copy()
for i in range(m):
  u[i] = round(np.exp(-np.pi**2*0.5)*np.sin(np.pi*x[i]),7)
  
print(u)

[0.        0.0022224 0.0042273 0.0058184 0.0068399 0.0071919 0.0068399
 0.0058184 0.0042273 0.0022224 0.       ]


In [11]:
diff = np.abs(temp - u[1:-1])
diff

array([8.27233653e-05, 1.57305195e-04, 2.16491319e-04, 2.54540232e-04,
       2.67635907e-04, 2.54540232e-04, 2.16491319e-04, 1.57305195e-04,
       8.27233653e-05])

In [0]:
import pandas as pd

In [18]:
print(x.shape)
print(temp.shape)
print(u.shape)

(11,)
(9,)
(11,)


In [0]:
data = {"x":x[1:-1],"sol. aprox": np.round(temp, 6), "sol analitica": u[1:-1]}

In [0]:
tabla = pd.DataFrame(data)

In [0]:
tabla = tabla[["x", "sol. aprox", "sol analitica"]]

In [33]:
tabla

x  sol. aprox  sol analitica
0  0.1    0.002305       0.002222
1  0.2    0.004385       0.004227
2  0.3    0.006035       0.005818
3  0.4    0.007094       0.006840
4  0.5    0.007460       0.007192
5  0.6    0.007094       0.006840
6  0.7    0.006035       0.005818
7  0.8    0.004385       0.004227
8  0.9    0.002305       0.002222