In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# inputs
a = 0
b = 2
c = 0
d = 1
m = 5
n = 6
tol = 10**(-10)
max_iter = 100
tol

1e-10

In [3]:
# paso 1
h = float((b-a))/n
k = float((d-c))/m
print(h,k)

(0.3333333333333333, 0.2)


In [4]:
# paso 2  y 3
x = np.zeros(n+1)
y = np.zeros(m+1)

# i = 0:n , sumamos 1 al final 
#paso 2
for i in range(n+1): x[i] = a + i*h
#paso 3
for j in range(m+1): y[j] = c + j*k
print(x)
print(y)

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.        ]
[0.  0.2 0.4 0.6 0.8 1. ]


In [5]:
## numeracion de una matriz

w = np.zeros((n+1,m+1))
for i in range(n+1):
  for j in range(m+1):
    w[i,j] = x[i]*np.exp(y[j])#i+float(j)/10

np.around(w,decimals=5)

array([[0.     , 0.     , 0.     , 0.     , 0.     , 0.     ],
       [0.33333, 0.40713, 0.49727, 0.60737, 0.74185, 0.90609],
       [0.66667, 0.81427, 0.99455, 1.21475, 1.48369, 1.81219],
       [1.     , 1.2214 , 1.49182, 1.82212, 2.22554, 2.71828],
       [1.33333, 1.62854, 1.9891 , 2.42949, 2.96739, 3.62438],
       [1.66667, 2.03567, 2.48637, 3.03686, 3.70923, 4.53047],
       [2.     , 2.44281, 2.98365, 3.64424, 4.45108, 5.43656]])

In [6]:
# valores iniciales
w = np.zeros((n+1,m+1)) # para que cada columna represente un punto en x

# paso 4
# DEFINIR EL ORDEN : en este caso de abajo a arriba
for i in range(n+1):
  w[i,0] = x[i]  # u(x,0)
  w[i,m] = np.e*x[i]  # u(x,1)
for j in range(m+1):
  w[0,j] = 0   # u(0,y)
  w[n,j] = 2*np.exp(y[j])   # u(2,y)

np.around(w,decimals=5)

array([[0.     , 0.     , 0.     , 0.     , 0.     , 0.     ],
       [0.33333, 0.     , 0.     , 0.     , 0.     , 0.90609],
       [0.66667, 0.     , 0.     , 0.     , 0.     , 1.81219],
       [1.     , 0.     , 0.     , 0.     , 0.     , 2.71828],
       [1.33333, 0.     , 0.     , 0.     , 0.     , 3.62438],
       [1.66667, 0.     , 0.     , 0.     , 0.     , 4.53047],
       [2.     , 2.44281, 2.98365, 3.64424, 4.45108, 5.43656]])

In [7]:
# paso 5
r = round(h**2/k**2,5)
u = round(2*(1+r),5)
print(r,u)

(2.77778, 7.55556)


In [0]:
# definir el f(x,y)
def f(x,y):
  return x*np.exp(y)

# definir el g(x,y)
def g(x,y):
  return x*np.exp(y)

[Gauss Seidel](https://www.maa.org/press/periodicals/loci/joma/iterative-methods-for-solving-iaxi-ibi-gauss-seidel-method)

In [9]:
z = (-h**2*f(x[1],y[m-1])+g(a,y[m-1])+r*g(x[1],d)+r*w[1,m-2]+w[2,m-1])/u
norm = abs(z-w[1,m-1])
w[1,m-1] = z
w

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.33333333, 0.        , 0.        , 0.        , 0.32221334,
        0.90609394],
       [0.66666667, 0.        , 0.        , 0.        , 0.        ,
        1.81218789],
       [1.        , 0.        , 0.        , 0.        , 0.        ,
        2.71828183],
       [1.33333333, 0.        , 0.        , 0.        , 0.        ,
        3.62437577],
       [1.66666667, 0.        , 0.        , 0.        , 0.        ,
        4.53046971],
       [2.        , 2.44280552, 2.9836494 , 3.6442376 , 4.45108186,
        5.43656366]])

In [10]:
for i in range(2,n-1):
    z = (-h**2*f(x[i],y[m-1])+r*g(x[i],d)+w[i-1,m-1]+w[i+1,m-1]+r*w[i,m-2])/u
    if abs(w[i,m-1] - z) > norm:
      norm = abs(w[i,m-1] - z)
    w[i,m-1] = z
w

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.33333333, 0.        , 0.        , 0.        , 0.32221334,
        0.90609394],
       [0.66666667, 0.        , 0.        , 0.        , 0.68707253,
        1.81218789],
       [1.        , 0.        , 0.        , 0.        , 1.05757602,
        2.71828183],
       [1.33333333, 0.        , 0.        , 0.        , 1.42882656,
        3.62437577],
       [1.66666667, 0.        , 0.        , 0.        , 0.        ,
        4.53046971],
       [2.        , 2.44280552, 2.9836494 , 3.6442376 , 4.45108186,
        5.43656366]])

In [11]:
z = (-h**2*f(x[n-1],y[m-1])+g(b,y[m-1])+r*g(x[n-1],d)+w[n-2,m-1]+r*w[n-1,m-2])/u
if abs(w[n-1,m-1] - z) > norm:
    norm = abs(w[n-1,m-1] - z)
w[n-1,m-1] = z
w

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.33333333, 0.        , 0.        , 0.        , 0.32221334,
        0.90609394],
       [0.66666667, 0.        , 0.        , 0.        , 0.68707253,
        1.81218789],
       [1.        , 0.        , 0.        , 0.        , 1.05757602,
        2.71828183],
       [1.33333333, 0.        , 0.        , 0.        , 1.42882656,
        3.62437577],
       [1.66666667, 0.        , 0.        , 0.        , 2.38928939,
        4.53046971],
       [2.        , 2.44280552, 2.9836494 , 3.6442376 , 4.45108186,
        5.43656366]])

In [12]:
#paso 10
# para j=2:-1:m-2 , se debe restar 1 al final para el range
for j in range(m-2,1,-1):
  #paso 11
  z = (-h**2*f(x[1],y[j])+g(a,y[j])+r*w[1,j+1]+r*w[1,j-1]+w[2,j])/u
  if abs(w[1,j]-z) > norm:
    norm = abs(w[1,j]-z)
  w[1,j] = z
  #paso 12
  for i in range(2,n-1):
    z = (-h**2*f(x[i],y[j])+w[i-1,j]+r*w[i,j+1]+w[i+1,j]+r*w[i,j-1])/u
    if abs(w[i,j]-z) > norm:
      norm = abs(w[i,j]-z)
    w[i,j] = z
  #paso 13
  z = (-h**2*f(x[n-1],y[j])+g(b,y[j]) +w[n-2,j]+r*w[n-1,j+1]+r*w[n-1,j-1])/u
  if abs(w[n-1,j]-z) > norm:
    norm = abs(w[n-1,j]-z)
  w[n-1,j] = z
w

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.33333333, 0.        , 0.03295511, 0.10952886, 0.32221334,
        0.90609394],
       [0.66666667, 0.        , 0.08136571, 0.24923281, 0.68707253,
        1.81218789],
       [1.        , 0.        , 0.13405309, 0.39500562, 1.05757602,
        2.71828183],
       [1.33333333, 0.        , 0.18770279, 0.54185632, 1.42882656,
        3.62437577],
       [1.66666667, 0.        , 0.89339289, 1.38779717, 2.38928939,
        4.53046971],
       [2.        , 2.44280552, 2.9836494 , 3.6442376 , 4.45108186,
        5.43656366]])

In [13]:
# Paso 14
z =(-h**2*f(x[1],y[1])+ g(a,y[1])+r*g(x[1],c)+r*w[1,2]+w[2,1])/u
if abs(w[1,1]-z) > norm:
  norm = abs(w[1,1]-z)
w[1,1] = z
w

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.33333333, 0.12867763, 0.03295511, 0.10952886, 0.32221334,
        0.90609394],
       [0.66666667, 0.        , 0.08136571, 0.24923281, 0.68707253,
        1.81218789],
       [1.        , 0.        , 0.13405309, 0.39500562, 1.05757602,
        2.71828183],
       [1.33333333, 0.        , 0.18770279, 0.54185632, 1.42882656,
        3.62437577],
       [1.66666667, 0.        , 0.89339289, 1.38779717, 2.38928939,
        4.53046971],
       [2.        , 2.44280552, 2.9836494 , 3.6442376 , 4.45108186,
        5.43656366]])

In [14]:
# Paso 15
for i in range(2,n-1):
  z = (-h**2*f(x[i],y[1])+r*g(x[i],c)+w[i-1,1]+r*w[i,2]+w[i+1,1])/u
  if abs(w[i,1]-z) > norm:
    norm = abs(w[i,1]-z)
  w[i,1] = z
w

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.33333333, 0.12867763, 0.03295511, 0.10952886, 0.32221334,
        0.90609394],
       [0.66666667, 0.28006828, 0.08136571, 0.24923281, 0.68707253,
        1.81218789],
       [1.        , 0.43603741, 0.13405309, 0.39500562, 1.05757602,
        2.71828183],
       [1.33333333, 0.59296631, 0.18770279, 0.54185632, 1.42882656,
        3.62437577],
       [1.66666667, 0.        , 0.89339289, 1.38779717, 2.38928939,
        4.53046971],
       [2.        , 2.44280552, 2.9836494 , 3.6442376 , 4.45108186,
        5.43656366]])

In [15]:
z = (-h**2*f(x[n-1],y[1])+g(b,y[1])+r*g(x[n-1],c)+w[n-2,1]+r*w[n-1,2])/u
if abs(w[n-1,1]-z) > norm:
  norm = abs(w[n-1,1]-z)
w[n-1,1] = z
w

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.33333333, 0.12867763, 0.03295511, 0.10952886, 0.32221334,
        0.90609394],
       [0.66666667, 0.28006828, 0.08136571, 0.24923281, 0.68707253,
        1.81218789],
       [1.        , 0.43603741, 0.13405309, 0.39500562, 1.05757602,
        2.71828183],
       [1.33333333, 0.59296631, 0.18770279, 0.54185632, 1.42882656,
        3.62437577],
       [1.66666667, 1.31305534, 0.89339289, 1.38779717, 2.38928939,
        4.53046971],
       [2.        , 2.44280552, 2.9836494 , 3.6442376 , 4.45108186,
        5.43656366]])

In [16]:
#paso 6
l = 1
while l <= max_iter :
  # paso 7 gauss seidel
  z = (-h**2*f(x[1],y[m-1])+g(a,y[m-1])+r*g(x[1],d)+r*w[1,m-2]+w[2,m-1])/u
  norm = abs(z-w[1,m-1])
  w[1,m-1] = z
  #paso 8
  for i in range(2,n-1):
    z = (-h**2*f(x[i],y[m-1])+r*g(x[i],d)+w[i-1,m-1]+w[i+1,m-1]+r*w[i,m-2])/u
    if abs(w[i,m-1] - z) > norm:
      norm = abs(w[i,m-1] - z)
    w[i,m-1] = z
  #paso 9 
  z = (-h**2*f(x[n-1],y[m-1])+g(b,y[m-1])+r*g(x[n-1],d)+w[n-2,m-1]+r*w[n-1,m-2])/u
  if abs(w[n-1,m-1] - z) > norm:
      norm = abs(w[n-1,m-1] - z)
  w[n-1,m-1] = z
  
  #paso 10
  # para j=2:-1:m-2 , se debe restar 1 al final para el range
  for j in range(m-2,1,-1):
    #paso 11
    z = (-h**2*f(x[1],y[j])+g(a,y[j])+r*w[1,j+1]+r*w[1,j-1]+w[2,j])/u
    if abs(w[1,j]-z) > norm:
      norm = abs(w[1,j]-z)
    w[1,j] = z
    #paso 12
    for i in range(2,n-1):
      z = (-h**2*f(x[i],y[j])+w[i-1,j]+r*w[i,j+1]+w[i+1,j]+r*w[i,j-1])/u
      if abs(w[i,j]-z) > norm:
        norm = abs(w[i,j]-z)
      w[i,j] = z
    #paso 13
    z = (-h**2*f(x[n-1],y[j])+g(b,y[j]) +w[n-2,j]+r*w[n-1,j+1]+r*w[n-1,j-1])/u
    if abs(w[n-1,j]-z) > norm:
      norm = abs(w[n-1,j]-z)
    w[n-1,j] = z
  # Paso 14
  z =(-h**2*f(x[1],y[1])+ g(a,y[1])+r*g(x[1],c)+r*w[1,2]+w[2,1])/u
  if abs(w[1,1]-z) > norm:
    norm = abs(w[1,1]-z)
  w[1,1] = z
  # Paso 15
  for i in range(2,n-1):
    z = (-h**2*f(x[i],y[1])+r*g(x[i],c)+w[i-1,1]+r*w[i,2]+w[i+1,1])/u
    if abs(w[i,1]-z) > norm:
      norm = abs(w[i,1]-z)
    w[i,1] = z

  # Paso 16
  z = (-h**2*f(x[n-1],y[1])+g(b,y[1])+r*g(x[n-1],c)+w[n-2,1]+r*w[n-1,2])/u
  if abs(w[n-1,1]-z) > norm:
    norm = abs(w[n-1,1]-z)
  w[n-1,1] = z

  if norm <= tol:
    print('termino en iteracion: ',l)
    break
  else:
    l = l + 1

('termino en iteracion: ', 60)


In [17]:
norm

9.105649567686669e-11

In [18]:
np.around(w,decimals=5)

array([[0.     , 0.     , 0.     , 0.     , 0.     , 0.     ],
       [0.33333, 0.40726, 0.49748, 0.6076 , 0.74201, 0.90609],
       [0.66667, 0.81452, 0.99496, 1.21518, 1.48401, 1.81219],
       [1.     , 1.22177, 1.4924 , 1.82274, 2.22599, 2.71828],
       [1.33333, 1.62896, 1.98978, 2.43023, 2.96793, 3.62438],
       [1.66667, 2.03604, 2.48696, 3.03751, 3.70972, 4.53047],
       [2.     , 2.44281, 2.98365, 3.64424, 4.45108, 5.43656]])

### Metodo matricial usando librerias

In [0]:
def tridiag(a,b,c,N):
    A = np.zeros([N,N])
    np.fill_diagonal(A[1:,:-1],a)
    np.fill_diagonal(A[:-1,1:],c)
    np.fill_diagonal(A,b)
    return A

In [20]:
A = tridiag(-r,u,-r,4)
A

array([[ 7.55556, -2.77778,  0.     ,  0.     ],
       [-2.77778,  7.55556, -2.77778,  0.     ],
       [ 0.     , -2.77778,  7.55556, -2.77778],
       [ 0.     ,  0.     , -2.77778,  7.55556]])

In [0]:
import scipy

In [0]:
mA = scipy.linalg.block_diag(A,A,A,A,A)

In [23]:
mU = -np.diag(np.ones(16),4)
mU.shape

(20, 20)

In [24]:
mL = -np.diag(np.ones(16),-4)
mL.shape

(20, 20)

In [25]:
fm =mL+mU+mA
fm[:6,:6]

array([[ 7.55556, -2.77778,  0.     ,  0.     , -1.     ,  0.     ],
       [-2.77778,  7.55556, -2.77778,  0.     ,  0.     , -1.     ],
       [ 0.     , -2.77778,  7.55556, -2.77778,  0.     ,  0.     ],
       [ 0.     ,  0.     , -2.77778,  7.55556,  0.     ,  0.     ],
       [-1.     ,  0.     ,  0.     ,  0.     ,  7.55556, -2.77778],
       [ 0.     , -1.     ,  0.     ,  0.     , -2.77778,  7.55556]])

In [26]:
#b = np.array([25,50,150,0,0,50,0,0,25])
b = np.array([w[0,1]+r*w[1,0],w[0,2],w[0,3],w[0,4]+r*w[1,5],r*w[2,0],0,0,r*w[2,5],r*w[3,0],0,0,r*w[3,5],r*w[4,0],0,0,r*w[4,5],w[6,1]+r*w[5,0],w[6,2],w[6,3],w[6,4]+r*w[5,5]])
b.shape

(20,)

In [0]:
h2f = np.zeros(20)
indice = 0
for i in range(1,n):
  for j in range(1,m):
    h2f[indice] = -h**2*f(x[i],y[j])
    indice = indice+1

In [28]:
b

array([ 0.92592667,  0.        ,  0.        ,  2.51692963,  1.85185333,
        0.        ,  0.        ,  5.03385926,  2.77778   ,  0.        ,
        0.        ,  7.5507889 ,  3.70370667,  0.        ,  0.        ,
       10.06771853,  7.07243885,  2.9836494 ,  3.6442376 , 17.03573002])

In [30]:
np.around(np.linalg.solve(fm,b+h2f),decimals=6)

array([0.407265, 0.497483, 0.607596, 0.742007, 0.814524, 0.994958,
       1.215183, 1.484009, 1.221766, 1.492405, 1.822743, 2.225993,
       1.628964, 1.989778, 2.430227, 2.967928, 2.036042, 2.486959,
       3.037506, 3.709724])

In [36]:
mis_i = []
mis_j =[]
for i in range(1,6):
  for j in range(1,5):
    mis_i.append(i)
    mis_j.append(j)
mis_i

[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5]

In [40]:
x

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        ])

In [44]:
nx = []
ny = []
for i in range(1,6):
  for j in range(1,5):
    nx.append(x[i])
    ny.append(round(y[j],6))
ny

[0.2,
 0.4,
 0.6,
 0.8,
 0.2,
 0.4,
 0.6,
 0.8,
 0.2,
 0.4,
 0.6,
 0.8,
 0.2,
 0.4,
 0.6,
 0.8,
 0.2,
 0.4,
 0.6,
 0.8]